CREATE TABLE  "COMPANY_MAILER_USER" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"PASSWORD" VARCHAR2(4000), 
	"GENDER" VARCHAR2(4000), 
	"DOB" DATE, 
	"ADDRESSLINE" VARCHAR2(4000), 
	"CITY" VARCHAR2(4000), 
	"STATE" VARCHAR2(4000), 
	"COUNTRY" VARCHAR2(4000), 
	"CONTACT" VARCHAR2(4000), 
	"REGISTEREDDATE" DATE, 
	"AUTHORIZED" VARCHAR2(4000), 
	 CONSTRAINT "COMPANY_MAILER_USER_PK" PRIMARY KEY ("ID") ENABLE
   )
/

CREATE TABLE  "COMPANY_MAILER_MESSAGE" 
   (	"ID" NUMBER, 
	"SENDER" VARCHAR2(4000), 
	"RECEIVER" VARCHAR2(4000), 
	"SUBJECT" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"TRASH" VARCHAR2(4000), 
	"MESSAGEDATE" DATE, 
	 CONSTRAINT "COMPANY_MAILER_MESSAGE_PK" PRIMARY KEY ("ID") ENABLE
   )
/

create sequence COMPANY_MAILER_USER_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER COMPANY_MAILER_USER_on_insert
  BEFORE INSERT ON COMPANY_MAILER_USER
  FOR EACH ROW
BEGIN
  SELECT COMPANY_MAILER_USER_ID_SEQ.nextval
  INTO :new.id
  FROM dual;
END;
/

create sequence MAILER_MESSAGE_ID_SEQ start with 1 increment by 1;

CREATE OR REPLACE TRIGGER MAILER_MESSAGE_on_insert
  BEFORE INSERT ON COMPANY_MAILER_MESSAGE
  FOR EACH ROW
BEGIN
  SELECT MAILER_MESSAGE_ID_SEQ.nextval
  INTO :new.id
  FROM dual;
END;
/

DELETE FROM COMPANY_MAILER_USER; 
INSERT INTO COMPANY_MAILER_USER (ID, NAME,EMAIL,PASSWORD,GENDER,DOB,ADDRESSLINE,CITY,STATE,COUNTRY,CONTACT,REGISTEREDDATE,AUTHORIZED) 
VALUES (1,'Alakeswari','alakeswari@cmailer.com','password','female',TO_DATE('15-AUG-95','DD-MON-RR'),'Panathur','Bangalore','Karnataka','India','998877661',TO_DATE('10-AUG-16','DD-MON-RR'),'yes');
INSERT INTO COMPANY_MAILER_USER (ID, NAME,EMAIL,PASSWORD,GENDER,DOB,ADDRESSLINE,CITY,STATE,COUNTRY,CONTACT,REGISTEREDDATE,AUTHORIZED) 
VALUES (2,'Neetu','neetu@cmailer.com','password','female',TO_DATE('15-AUG-95','DD-MON-RR'),'Panathur','Bangalore','Karnataka','India','998877662',TO_DATE('10-AUG-16','DD-MON-RR'),'yes');
COMMIT;

INSERT INTO COMPANY_MAILER_MESSAGE (ID,SENDER,RECEIVER,SUBJECT,MESSAGE,TRASH,MESSAGEDATE) 
VALUES (1,'alakeswari@cmailer.com','neetu@cmailer.com','Reminder','Hey, Tomorrow is project submission, Dont forget pen drive.','no',TO_DATE('16-AUG-16','DD-MON-RR'));
INSERT INTO COMPANY_MAILER_MESSAGE (ID,SENDER,RECEIVER,SUBJECT,MESSAGE,TRASH,MESSAGEDATE) 
VALUES (2,'neetu@cmailer.com','alakeswari@cmailer.com','Sure','Sure, Thanks for reminding :)','no',TO_DATE('16-AUG-16','DD-MON-RR'));
